basic:
    name: 'https://www.luthermanor.org/'
    environments:
        production: 'https://www.luthermanor.org/'
        staging: 'https://gyznxviri2.wpdns.site/'
        development: ''
    basicAuth:
        production: { user: '', password: '' }
        staging: { user: '', password: '' }
        development: { user: '', password: '' }
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /
        - /contact-us
        - /blog
        - /events
        - /careers
        - /independent-living
        - /independent-living/floor-plans
        - /assisted-living
        - /assisted-living/the-courtyards
        - /memory-care
        - /health-services
        - /hospice-care
        - /support
        - /donate
        - /volunteer
        - /about-us
        - /senior-living-resources
        - /coronavirus
        - /blog/soulful-living-the-role-of-spirituality-in-retirement
        - /blog/the-perks-of-a-rental-contract-at-luther-manor
        - /blog/assisted-living-vs-memory-care
        - /privacy-policy
        - /html-sitemap
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    delay: 10
    scroll: false
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: '30'
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
